from pydantic import BaseModel, Field


class ScreeningRequest(BaseModel):
    resume_text: str = Field(
        ...,
        description="Raw candidate resume text",
        json_schema_extra={"example": "5 years experience in Python, FastAPI, PostgreSQL."}
    )
    job_description: str = Field(
        ...,
        description="Job posting requirements and responsibilities",
        json_schema_extra={"example": "Looking for a Python Backend Engineer."}
    )


class ScreeningResponse(BaseModel):
    verdict: str = Field(..., description="Screening verdict and supporting reasons generated by LangGraph agent")
